Move add action on Trigger inside Trigger Detail Fragment #113
hawkular/hawkular-android-client pull request #132
Opened 2017-03-10 09:47 UTC by pg301

Move add action on Trigger inside Trigger Detail Fragment #113

2017-03-10 13:51 UTC, danielpassos requested changes

2017-03-10 13:51 UTC, danielpassos commented on mobile/src/main/java/org/hawkular/client/android/Animae/MyBounceInterpolator.java
> +/*
1. Never use camel case for package name
1. Let's rename the package for _animation_

2017-03-10 13:51 UTC, danielpassos commented on mobile/src/main/java/org/hawkular/client/android/fragment/TriggerDetailFragment.java
> +    ImageButton button;
Let's avoid to use generic names like _button_. Let's use something that really represent button action like _addButton_

2017-03-10 13:51 UTC, danielpassos commented on mobile/src/main/java/org/hawkular/client/android/fragment/TriggerDetailFragment.java
> +    TextView textView;
Same for this one!

2017-03-10 13:51 UTC, danielpassos commented on mobile/src/main/java/org/hawkular/client/android/fragment/TriggerDetailFragment.java
> +        setUpBindings();
I wanna start to kill this kind of unecessarly methods like I did here: https://github.com/hawkular/hawkular-android-client/pull/129

So... I'll like suggest you to kill this method and move the content to `onCreateView`

```java
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
    View view =  inflater.inflate(R.layout.fragment_trigger_detail, container, false);
    ButterKnife.bind(this, view);
    return view;
}
```

2017-03-10 13:51 UTC, danielpassos commented on mobile/src/main/res/drawable/ic_favorite_black_24dp.xml
> +<!--
Should remove `black_24dp` from the name of the file. Should be `ic_favorite`

2017-03-10 13:51 UTC, danielpassos commented on mobile/src/main/res/layout/fragment_trigger_detail.xml
> +</LinearLayout>
Add newline at the end of the file

2017-03-10 20:49 UTC, shubhamvashisht commented
@pg301 waiting for this issue to be resolved so that i can start working on issue assigned to me.

2017-03-14 11:23 UTC, pg301 commented
@danielpassos @garg-anuj  I have done the requested changes, please have a look.

P.S. Sorry for the delay in response.

2017-03-14 11:59 UTC, pilhuhn commented
@pg301 I think it would be better to give a quick summary of changes as you did in other comments and not only write "Changes in #113". This way it is easier in the commit log to understand what is done.

2017-03-14 12:08 UTC, pg301 commented
@pilhuhn Thanks for the advice sir, will keep this in mind.

2017-03-14 12:17 UTC, pg301 commented
@garg-anuj @danielpassos I think the issue is fixed. Please have a look and let me know if some more changes are required.

2017-03-14 13:18 UTC, garg-anuj commented
@pg301 Can you please also attach gif for this PR?

2017-03-14 13:23 UTC, KeenWarrior approved these changes
Looking good to me

2017-03-14 14:31 UTC, pg301 commented
![demo1_new](https://cloud.githubusercontent.com/assets/10026907/23905323/b47765e6-08f0-11e7-9dae-4c167d271481.gif)
@garg-anuj here's the gif

2017-03-14 14:36 UTC, garg-anuj commented
@danielpassos any comments?

2017-03-15 13:24 UTC, danielpassos commented
![](https://github.com/danielpassos/reaction-gifs/blob/master/hi-5-as-team.gif?raw=true)

2017-03-15 13:24 UTC, danielpassos approved these changes

2017-03-15 13:26 UTC, merged

2017-03-15 16:25 UTC, pg301 commented
@danielpassos @garg-anuj Thanks :)