Lists updated instantly.
hawkular/hawkular-android-client pull request #172
Opened 2017-03-19 22:49 UTC by free4murad

Fixes issue #171 

Please review.

2017-03-19 22:50 UTC, free4murad commented on mobile/src/main/java/org/hawkular/client/android/fragment/TriggerDetailFragment.java
> -import android.widget.TextView;
This was an unused import statement.

2017-03-19 22:52 UTC, free4murad commented on mobile/src/main/java/org/hawkular/client/android/fragment/TriggersFragment.java
> +        store.close();
`store` was not closed earlier.
This was causing resource leaks.

2017-03-20 13:20 UTC, free4murad commented on mobile/src/main/java/org/hawkular/client/android/fragment/TriggerDetailFragment.java
> -import android.widget.Toast;
These were unused imports.

2017-03-21 16:14 UTC, garg-anuj commented on mobile/src/main/java/org/hawkular/client/android/fragment/TriggersFragment.java
> +        store.close();
It is generally good to avoid mixing different works in PR :)

2017-03-21 19:07 UTC, free4murad commented on mobile/src/main/java/org/hawkular/client/android/fragment/TriggersFragment.java
> +        store.close();
@garg-anuj 
Sure
I will update the PR and send a new PR for resource leak.

2017-03-22 14:07 UTC, KeenWarrior requested changes

2017-03-22 14:07 UTC, garg-anuj commented on mobile/src/main/java/org/hawkular/client/android/fragment/TriggersFragment.java
> +        }
corresponding else case is missing

2017-03-22 22:03 UTC, free4murad commented
@garg-anuj 
Done

2017-03-23 17:09 UTC, garg-anuj commented on mobile/src/main/java/org/hawkular/client/android/fragment/TriggersFragment.java
> +    @Override public void onResume() {
@free4murad Why you put `@Override` in same line of method everytime :laughing:

2017-03-23 17:28 UTC, free4murad commented on mobile/src/main/java/org/hawkular/client/android/fragment/TriggersFragment.java
> +    @Override public void onResume() {
Sorry I think there is some issue with Android studio on my laptop.
I will make sure that it doesn't happen again

2017-04-07 09:55 UTC, KeenWarrior approved these changes

2017-04-07 09:55 UTC, merged